language: objective-c
osx_image: xcode12.2

before_install:
  - gem install slather

script:
  - set -o pipefail;
  - xcodebuild test -project Source/OCHamcrest.xcodeproj -scheme OCHamcrest -sdk macosx | xcpretty
  - xcodebuild build -project Source/OCHamcrest.xcodeproj -scheme OCHamcrest-iOS -sdk iphonesimulator -destination "platform=iOS Simulator,OS=latest,name=iPhone 8" | xcpretty
  - xcodebuild build -project Source/OCHamcrest.xcodeproj -scheme OCHamcrest-tvOS -sdk tvossimulator -destination "platform=tvOS Simulator,OS=latest,name=Apple TV" | xcpretty
  - pod spec lint --quick

after_success:
  - slather
