language: objective-c

before_install:
  - sudo easy_install cpp-coveralls

script:
  - xctool test -project Source/OCHamcrest.xcodeproj -scheme OCHamcrest -sdk macosx10.9

after_success:
  - ./coveralls.rb --exclude-folder Source/Tests
